openapi: 3.0.3
info:
  title: Marketplace Products
  description: Marketplace of products
  version: 0.0.1
paths:
  /products/{productId}:
    get:
      summary: Get a product by UUID
      operationId: getProduct
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Found product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
